Add Efinity and Westfinity SS58 address prefix
paritytech/ss58-registry pull request #48
Opened 2021-11-16 23:59 UTC by coinfork

Hello everyone,

The Enjin team would like to add our SS58 prefixes for Efinity (Polkadot) and Westfinity (Westend).
Project website: efinity.io

Thank you!

2021-11-17 07:43 UTC, joepetrowski requested changes

2021-11-17 07:43 UTC, joepetrowski commented on ss58-registry.json
> +      "prefix": 1110,
Not in order

2021-11-17 07:43 UTC, joepetrowski commented on ss58-registry.json
> +      "website": "https://efinity.io/"
I don't think testnets should have a prefix reserved

2021-11-19 04:18 UTC, BenWhiteJam commented
@coinfork any update on the comments?

2021-11-19 05:03 UTC, coinfork commented
> @coinfork any update on the comments?

Fixed!

2021-11-24 17:23 UTC, joepetrowski approved these changes

2021-12-06 08:16 UTC, BenWhiteJam approved these changes

2021-12-06 08:44 UTC, bkchr approved these changes

2021-12-06 08:44 UTC, merged